-add resend logic for not delivery message.
youagree/qr-entry-control pull request #17
Opened 2021-05-31 17:56 UTC by youagree

-add resend logic for not delivery message.

author: uber-dev
Issue: qec-3

2021-05-31 18:32 UTC, PavelSoldatov requested changes

2021-05-31 18:32 UTC, PavelSoldatov commented on qr-entry-control-impl/src/main/java/ru/unit_techno/qr_entry_control_imp/repository/QrDeliveryEntityRepository.java
> +    @Query("update QrDeliveryEntity qr set qr.deliveryStatus = deliveryStatus where qr.messageTag = uuid")
Перед параметрами надо ставить ":", чтобы они подтягивались, иначе будет невалидный запрос

2021-05-31 18:32 UTC, PavelSoldatov commented on qr-entry-control-impl/src/main/java/ru/unit_techno/qr_entry_control_imp/scheduler/MessageScheduler.java
> +                    messageStorageService.deleteSuccessDeliveryMessage(stringQrPictureObjectEntry.getKey());
А есть уверенность, что оно 100% отправится? Ты удаляешь его будучи не уверенным в успешной отправке

2021-05-31 18:32 UTC, PavelSoldatov commented on qr-entry-control-impl/src/main/java/ru/unit_techno/qr_entry_control_imp/service/QrEmailService.java
> +            sendHtmlMessage(to, subject, htmlBody, qrPictureObject.getFilePath());
Оно не ассинхронно работает? Нет вероятности, что мы узнаем, что оно не отправилось уже после того, как ты обновишь статус в следующей строчке?

2021-05-31 18:32 UTC, PavelSoldatov commented on qr-entry-control-impl/src/main/java/ru/unit_techno/qr_entry_control_imp/service/QrService.java
> +                .setDeliveryStatus(DeliveryStatus.NOT_DELIVERED)
Ты в итоге в сущности QrCodeEntity проставишь NOT_DELIVERED, а в новой своей таблице проставишь DELIVERED, при успешной отправке. Получится одно и то же сообщение будет и не отправлено и отправлено. Нужно добавить смену статуса и в этой сущности при успешной отправке

2021-05-31 19:24 UTC, youagree commented on qr-entry-control-impl/src/main/java/ru/unit_techno/qr_entry_control_imp/repository/QrDeliveryEntityRepository.java
> +    @Query("update QrDeliveryEntity qr set qr.deliveryStatus = deliveryStatus where qr.messageTag = uuid")
добавил

2021-06-01 18:52 UTC, PavelSoldatov approved these changes

2021-06-02 19:43 UTC, merged